Trint(f,type,xlim,ylim,zlim):=block(

if type =1 then 
    (f1:integrate(f, z,zlim[1],zlim[2]), 
    f2:integrate(f1, x,xlim[1],xlim[2]),
    integrate(f2, y,ylim[1],ylim[2])) 
else if type = 2 then 
(f1:integrate(f, x,xlim[1],xlim[2]),
f2:integrate(f1, z,zlim[1],zlim[2]),
integrate(f2, y,ylim[1],ylim[2]))
else if type = 3 then 
(f1:integrate(f, y,ylim[1],ylim[2]),
f2:integrate(f1, z,zlim[1],zlim[2]),
integrate(f2, x,xlim[1],xlim[2]))
else
disp("Error: type must be 1 or 2 or 3 only!")); 